<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ArticleTranslation extends Model
{
    use HasFactory;
    use SoftDeletes;

    public $timestamps = false;
    protected $fillable = ['title','slug','lead','body','keywords','status', 'published_at','publish_at'];

    public function article(){
        return $this->belongsTo(Article::class);
    }

    protected $casts = [
        'publish_at' => 'datetime',
        'keywords' => 'json'
    ];

    public function toArray() {
        return parent::toArray(); // TODO: Change the autogenerated stub
    }

    public function scopePublished($query)
    {
        return $query->where('status','=','p');
    }

    public function vzt()
    {
        return visits($this);
    }
}
